version: 2.1 
jobs:
  build:
    working_directory: ~/app 
    docker:
      - image: circleci/node:10.15.3
    steps: # a collection of executable commands
        - checkout
        - run:
            name: update-npm
            command: 'sudo npm install -g npm@latest'
        - run:
            name: install
            command: 'npm install'
        - run: 
            name: linter
            command: npm run lint
        - run:
            name: testing
            command: npm run test:single
